# Generated by Django 6.0.3 on 2026-03-21 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_category_metadata(apps, schema_editor):
    Category = apps.get_model("boomers", "Category")
    for category in Category.objects.all():
        normalized = " ".join((category.name or "").strip().lower().split())
        category.normalized_name = normalized
        if not category.is_default and category.owner_id is None:
            category.is_shared = True
        category.save(update_fields=["normalized_name", "is_shared"])


class Migration(migrations.Migration):
    dependencies = [
        ("boomers", "0002_boomer_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(populate_category_metadata, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", False)),
                fields=("owner", "normalized_name"),
                name="unique_owner_normalized_category",
            ),
        ),
    ]
